sudo: false
dist: trusty
language: node_js
node_js:
- 4.3.2
- lts/argon
- lts/boron
- '7'
cache:
  yarn: true
  directories:
  - test/fixtures
after_success: |
  #if [ ]; then
    #yarn run coverage
    #openssl aes-256-cbc -K $encrypted_752f08bd0f71_key -iv $encrypted_752f08bd0f71_iv -in deploy_key.enc -out deploy_key -d
    echo $TRAVIS_NODE_VERSION
  #fi

addons:
  code_climate:
    repo_token: ""
