language: node_js
node_js:
  - "0.10.36"
before_script:
  - npm install -g gulp
#script:
  #- npm run-script coverage
  #- "`npm bin`/coveralls < coverage/lcov.info"
addons:
    code_climate:
        repo_token: 41b073ed873540cfbac2c98ab1c7c79b3e894bebc7b462bd04f5988650270385