language: node_js
node_js:
  - "4.3.2"
cache:
  directories:
    - node_modules
    - test/fixtures
after_success: npm run coverage
addons:
  code_climate:
    repo_token: 41b073ed873540cfbac2c98ab1c7c79b3e894bebc7b462bd04f5988650270385